// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payment/payment.proto

package payment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	header "github.com/rakamoviz/esproto/header"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PaymentReceived struct {
	Header               *header.Event `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PaymentReceived) Reset()         { *m = PaymentReceived{} }
func (m *PaymentReceived) String() string { return proto.CompactTextString(m) }
func (*PaymentReceived) ProtoMessage()    {}
func (*PaymentReceived) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a39aceed8019db, []int{0}
}

func (m *PaymentReceived) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentReceived.Unmarshal(m, b)
}
func (m *PaymentReceived) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentReceived.Marshal(b, m, deterministic)
}
func (m *PaymentReceived) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentReceived.Merge(m, src)
}
func (m *PaymentReceived) XXX_Size() int {
	return xxx_messageInfo_PaymentReceived.Size(m)
}
func (m *PaymentReceived) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentReceived.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentReceived proto.InternalMessageInfo

func (m *PaymentReceived) GetHeader() *header.Event {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterType((*PaymentReceived)(nil), "paymentproto.payment.PaymentReceived")
}

func init() {
	proto.RegisterFile("payment/payment.proto", fileDescriptor_66a39aceed8019db)
}

var fileDescriptor_66a39aceed8019db = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x48, 0xac, 0xcc,
	0x4d, 0xcd, 0x2b, 0xd1, 0x87, 0xd2, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x22, 0x50, 0x2e,
	0x98, 0xa7, 0x07, 0xe5, 0x48, 0x99, 0x97, 0xa5, 0xe6, 0xa5, 0xe4, 0x17, 0xe9, 0xa7, 0x67, 0x96,
	0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x17, 0x25, 0x66, 0x27, 0xe6, 0xe6, 0x97, 0x65,
	0x56, 0xe9, 0xa7, 0x16, 0x83, 0x15, 0xeb, 0x67, 0xa4, 0x26, 0xa6, 0xa4, 0x16, 0x41, 0x29, 0x88,
	0x71, 0x4a, 0x0e, 0x5c, 0xfc, 0x01, 0x10, 0x33, 0x82, 0x52, 0x93, 0x53, 0x33, 0xcb, 0x52, 0x53,
	0x84, 0x74, 0xb9, 0xd8, 0x20, 0x4a, 0x24, 0x18, 0x15, 0x18, 0x35, 0xb8, 0x8d, 0x44, 0xf5, 0xa0,
	0x06, 0xe8, 0x41, 0x75, 0xba, 0x96, 0x81, 0x94, 0x43, 0x15, 0x39, 0x69, 0x47, 0x69, 0x62, 0xb5,
	0x15, 0xd9, 0x9d, 0x30, 0x4e, 0x12, 0x1b, 0x98, 0x6b, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x5a,
	0x35, 0x69, 0x32, 0xdd, 0x00, 0x00, 0x00,
}
